export const FETCH_CH_GOMICS_PENDING = 'FETCH_CH_GOMICS_PENDING';
export const FETCH_CH_GOMICS_FULFILLED = 'FETCH_CH_GOMICS_FULFILLED';
export const FETCH_CH_GOMICS_REJECTED = 'FETCH_CH_GOMICS_REJECTED';
